name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        # Run all steps in the 'actions' subdirectory
        working-directory: ./actions

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          # Point the cache to the package-lock.json in the subdirectory
          cache-dependency-path: ./actions/package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test